language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3

sudo: false

cache:
  directories:
    - ~/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.1
      env: SONATA_MEDIA=~2.3

before_install:
  - phpenv config-rm xdebug.ini
  - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
  - composer self-update
  - composer global require "hirak/prestissimo:^0.3"
  - if [ "$SONATA_MEDIA" != "" ]; then composer require "sonata-project/media-bundle:${SONATA_MEDIA}" --dev --no-update; fi;
  - if [ "$COMPOSER_FLAGS" != "" ]; then composer update --prefer-dist --no-interaction --no-scripts $COMPOSER_FLAGS; fi;
  - composer install --prefer-dist --no-interaction --no-scripts

script: vendor/bin/phpunit
