language: php

sudo: false

cache:
  directories:
    - ~/.composer/cache/files
    
matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: deps='low'
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: 5.4
    - php: 5.3
      dist: precise

before_install:
  - phpenv config-rm xdebug.ini
  - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - if [[ ! $deps ]]; then composer update --prefer-dist --no-progress --no-suggest --ansi; fi
  - if [[ $deps = 'low' ]]; then composer update --prefer-dist --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi; fi

script:
  - vendor/bin/phpunit
